### ISSUE TITLE
reduce dependencies

### ISSUE THREAD

**Issue by jjallaire** [rstudio/fontawesome#1]
This set of dependencies seems quite large:

```
Imports:
    dplyr (>= 0.7.4),
    glue (>= 1.2.0),
    htmltools (>= 0.3.6),
    knitr (>= 1.20),
    magrittr,
    rlang (>= 0.2.0),
    stringr (>= 1.3.0)
```

It seems like for what we are doing here a much more minimal set of dependencies should be required. Could we pare this down?

**Comment by rich-iannone** [comment]
I definitely think so. I’ll pare down so we just have to import htmltools and knitr.

**Comment by jjallaire** [comment]
Okay, great!

I could be wrong about this, but since htmltools implements knit_print for tags you might not need the knitr dependency either.

**Comment by rich-iannone** [comment]
Ah, even better... hopefully it'll just depend on `htmltools` then.

**Comment by rich-iannone** [comment]
Rewrote the main function `fa()` to have only the dependency on `htmltools`. Will investigate doing the same for the knit_print method.

**Comment by jjallaire** [comment]
It seems to me as if you shouldn't require the `knit_print` method at all (since the object is already a tag and tag implements knit_print as well).

**Comment by wch** [comment]
FWIW, I believe that even if you have a `knit_print` method, you don't need to import anything from knitr.

**Comment by rich-iannone** [comment]
We needed to use `knitr::knit_print()` in order to workaround the issue of FontAwesome icons in header-level text. Without this method, the icon rendering in headings wasn't correct.

**Comment by jjallaire** [comment]
Okay, so if a Shiny application wants to use this package they would need to install knitr then?

What about making knitr suggests and doing a `requireNamespace()` around the use of `knitr::knit_print()`?

**Comment by rich-iannone** [comment]
The use of `requireNamespace()` has now been implemented.
