### ISSUE TITLE
Feature request: inherit style of element

### ISSUE THREAD

**Issue by jnolis** [rstudio/fontawesome#10]
Right now if I leave the color blank `fa("robot", fill=NULL)` then the color ends up being #000000. I would really like it to be the color of whatever element it's contained in (like if it's in the middle of an h1 block then have it take the same color as that text). It doesn't seem like there is a way to do this--can that functionality be added?

**Comment by rich-iannone** [comment]
Great suggestion, thanks for filing the issue! I’ll look into this soon, I’m sure it’s possible. I also agree that the default behavior should be to inherit the color of the parent element.

**Comment by rich-iannone** [comment]
I'm really sorry it took so long to fix this, but, it's fixed in https://github.com/rstudio/fontawesome/commit/458279eb7bd9b40b443a9203465ac78a25d861ba! Now, the default behavior is to inherit the `"currentColor"`.
