### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by RedTent** [rstudio/fontawesome#101]
I'd like to use some icons in the way of bullet points. To do this I need the icons to be aligned in the middle. In the current implementation the vertical alignment of the icons is hardcoded as -0.125 em. Which means there is no way for me to adjust the vertical alignment. 

Though -0.125 em is probably a good default it's keeping me from what I wanted to achieve.

Is it possible to include de vertical alignment also in the function arguments? I think that would solve my problem.

**Comment by rich-iannone** [comment]
Thanks for the suggestion. I think it’s a good idea and so we’ll implement this!
