### ISSUE TITLE
Error: could not find function "file.edit"

### ISSUE THREAD

**Issue by jpOmaha** [rstudio/fontawesome#11]
> devtools::install_github("rstudio/fontawesome")
Downloading GitHub repo rstudio/fontawesome@master
✔  checking for file ‘/private/var/folders/pm/v1r05mm553z8cv0t4p2x8cf00000gn/T/RtmpTAm6ML/remotes1715474502c28/rstudio-fontawesome-ba97af5/DESCRIPTION’ ...
─  preparing ‘fontawesome’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘fontawesome_0.1.0.tar.gz’
   
Error: could not find function "file.edit"
Execution halted
Error: Failed to install 'fontawesome' from GitHub:
  (converted from warning) installation of package ‘/var/folders/pm/v1r05mm553z8cv0t4p2x8cf00000gn/T//RtmpTAm6ML/file171543b8331c0/fontawesome_0.1.0.tar.gz’ had non-zero exit status
Called from: value[[3L]](cond)

**Comment by rich-iannone** [comment]
This seems like a spurious installation issue. Could you try the installation again?

**Comment by JessicaXue666** [comment]
Hi i met the same question, did you find the solution?
