### ISSUE TITLE
Front anwesome not correspond to a know icon

### ISSUE THREAD

**Issue by NhiNLU** [rstudio/fontawesome#120]
I use Mac OS:

I try to run cronR addins., but when I click Addin, it show up:

The 'name' provided ('clock-o') does not correspond to a known icon
The 'name' provided ('load') does not correspond to a known icon
The 'name' provided ('delete') does not correspond to a known icon

I use this version and all packages are updated
frontawesome_0.5.2 shiny_1.8.1.1

**Comment by rich-iannone** [comment]
I think cronR needs to update their code. Could you open an issue on their repo?
