### ISSUE TITLE
Dev version not loading fontawesome 6.5.2

### ISSUE THREAD

**Issue by AmeliaMN** [rstudio/fontawesome#121]
This could easily be a user error issue, because I don't install from GitHub very frequently. I'm trying to get fontawesome 6.5.2 so I can use `fa("bluesky")` on my Quarto website. I have tried

```
remove.packages("fontawesome")
devtools::install_github("rstudio/fontawesome", build = TRUE)
library(fontawesome)
fa_metadata()$version
[1] "6.4.2"
```

(both with and without the `build = TRUE`). Every time it tells me the fontawesome version is still 6.4.2, and when I run 

```
fa("bluesky")
```

I get 
```
Error: The `name` provided ('bluesky') does not correspond to a known icon
```

I can see in the repo that it should be updated to 6.5.2. Am I doing something wrong with my install?

**Comment by rich-iannone** [comment]
Just released fontawesome 0.5.3 so this should work now!
