### ISSUE TITLE
Integration with gt

### ISSUE THREAD

**Issue by charlesatkinson2000** [rstudio/fontawesome#14]
This is a great (and underrated) package and I stumbled onto it pretty much by accident. I use gt quite a bit and it could benefit by some integration with this package. Are there plans to provide examples and/or expanded support for fontawesome in gt?

**Comment by rich-iannone** [comment]
Sorry for not answering this sooner. It's always worked nicely with {gt}. Here is an example that uses the `sza` dataset and some Font Awesome icons are placed in the title.

``` r
library(gt)
library(fontawesome)

sza %>%
  dplyr::filter(latitude == 20) %>%
  dplyr::select(-latitude) %>%
  dplyr::filter(!is.na(sza)) %>%
  tidyr::spread(key = "tst", value = sza) %>%
  gt(rowname_col = "month") %>%
  fmt_missing(
    columns = TRUE,
    missing_text = ""
  ) %>%
  tab_stubhead(label = md("month<br>(20&deg;N)")) %>%
  tab_header(title = md(paste(fa("sun"), "Solar Zenith Angles", fa("sun")))) %>%
  tab_options(
    column_labels.font.size = "smaller",
    table.font.size = "smaller",
    data_row.padding = px(3)
  )
```

The resulting table looks like this:

<img width="763" alt="fa-sza" src="https://user-images.githubusercontent.com/5612024/109991630-7a34e880-7cd8-11eb-9c0a-5cdc0a426cea.png">

It's also possible, with the more recent changes, to style the icons. So, you can provide a color and other styling to the icon's outline (with `stroke`, `stroke_width`, and `stroke_opacity`) as well as providing a color for the `fill`. In the future, we'd like to provide even more options.
