### ISSUE TITLE
unable to install fontawesome for rstudio in ubuntu 18.04

### ISSUE THREAD

**Issue by dviresh** [rstudio/fontawesome#15]
Hello, 

I am new to R, and it is my first time trying to use it in linux. I am trying to run an app that I installed from shiny gallery. It uses font awesome. 

I tried installing fontawesome using the command -  devtools::install_github("rstudio/fontawesome")

But it fails. 

I have tried using by installing emojifont and then doing load.fontawesome(), but in this case I am not able to use the fa() function.

I am not sure where is the issue? Is it something specific to linux? or is it something specific to the rstudio version I am using? 

Any help from you will be greatly appreciated.

**Comment by rich-iannone** [comment]
Could you try again? It seems like you're using the right function to install the package.
