### ISSUE TITLE
Installed into R studio but still not running code

### ISSUE THREAD

**Issue by veronicapthomas** [rstudio/fontawesome#17]
I installed fontawesome and it is in my library but when I try to run this code:
waffle(
  c(`Poor=10` =10, `Average=18` = 18, `Excellent=7` =7), rows = 5, 
  colors = c("#FD6F6F", "#93FB98", "#D5D9DD"),use_glyph = "female", 
  glyph_size = 12 ,title = 'Girls Performance', legend_pos="bottom")

it gives me this error:
Error: FontAwesome not found. Install via: https://github.com/FortAwesome/Font-Awesome/tree/master/fonts

please advise.

**Comment by rich-iannone** [comment]
I think the problem here is with the `waffle` package. Please post an issue in: https://github.com/hrbrmstr/waffle.
