### ISSUE TITLE
Fail to knit `fontawesome`-icons to PDF

### ISSUE THREAD

**Issue by csatzky** [rstudio/fontawesome#20]
Hi there,

Thank you for the development of this _awesome_ package!

Unfortunately, I do not get the icons to render when I change the YAML syntax of [the README example](https://github.com/rstudio/fontawesome) to `output: pdf_document`.

I have created a [question on StackOverflow](https://stackoverflow.com/questions/65117169/fontawesome-icons-ignored-when-knitting-rmarkdown-to-pdf) regarding this issue.

Please delete if this issue has nothing to do with `fontawesome`.

Thank you.

Cheers,
Christian

**Comment by rich-iannone** [comment]
I'm sorry but these functions will only work in an HTML output context.
