### ISSUE TITLE
Should use GitHub actions to get newer versions of Font Awesome

### ISSUE THREAD

**Issue by wch** [rstudio/fontawesome#22]
There should be a GitHub Action that checks for a newer available version of Font-Awesome and either makes a PR for it automatically, or gives an alert if a newer version is available.

**Comment by schloerke** [comment]
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Comment by rich-iannone** [comment]
I'm now made aware of FontAwesome releases by watching for releases (I'm alerted through the notifications Inbox). Since this is pretty sufficient, going to close the issue.
