### ISSUE TITLE
Shorten package name

### ISSUE THREAD

**Issue by coatless** [rstudio/fontawesome#3]
Anyway the package name could be shorten from `fontawesome` to `fa`?

**Comment by rich-iannone** [comment]
I don’t know, I’ll already have a bunch of packages with very short names (e.g., **gt**, **ttt**)... Joking aside, I think what you want is `fa::fa(“icon”)`. However I think we went with **fontawesome** because **fa** wasn’t very recognizable as being FontAwesome.

**Comment by coatless** [comment]
Right you are, I'm looking for namespace prefixing. 

Not sure I agree with `fa` not being recognizable as each icon code is prefixed by `fa`. For example, the [`address-book`](https://fontawesome.com/icons/address-book?style=regular) icon in FontAwesome 5 is given with:

```html
<i class="far fa-address-book"></i>
```

If the worry is more about naming the core functionality after the package name, why not:

```r
fa::icon("address-book")
```

Generally, any _RStudio_ package should have improved visibility compared to traditional packages. So, I think even with name of `fa` that the package should be noticed. 

Regardless, this is a very useful package. Thanks for making it!

**Comment by rich-iannone** [comment]
@coatless I've had a discussion internally here and we've decided to stick with the slightly longer package name of **fontawesome**. 

I am hopeful that we can find other ways to generally shorten the amount of typing required in the function call itself.

**Comment by coatless** [comment]
@rich-iannone thanks for holding another conversation and the update!
