### ISSUE TITLE
`print()` method should use `cat()` instead of `message()`

### ISSUE THREAD

**Issue by wch** [rstudio/fontawesome#36]
The `print()` method should use `cat()` instead of `message()` here:
https://github.com/rstudio/fontawesome/blob/90b32558a8e6e0302fb489e37a50d872e0bad9fe/R/print.R#L41

**Comment by rich-iannone** [comment]
Thanks. Fixed in https://github.com/rstudio/fontawesome/commit/0760befa0d9071455ae9cdf0d2890af0fa1898f3.
