### ISSUE TITLE
SVG tags should be accessible

### ISSUE THREAD

**Issue by wch** [rstudio/fontawesome#38]
See "Better Accessibility" section in https://www.irigoyen.dev/blog/2021/02/17/stop-using-icon-fonts/

Some other resources:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img
https://www.deque.com/blog/creating-accessible-svgs/
https://www.tpgi.com/using-aria-enhance-svg-accessibility/

Maybe also allow users to pass in a title/tooltip/description. This is sort of orthogonal to accessibility per se, but could be handy for tooltips. For example:

```R
icon("question", title = "This thing does x, y, z")
```

**Comment by rich-iannone** [comment]
Here's another tip, from a Font Awesome page: `Note: to improve web accessibility, we recommend using aria-hidden="true" to hide icons used purely for decoration.`
