### ISSUE TITLE
Icons are not at the right place in Windows, IE11

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/fontawesome#39]
Install Fontawesome from cran and run shiny-test.R and test.Rmd from tests/manual_tests .  Icons which were supposed to be left of the labels are on the right and there is lot of space in between.

![CaptureIE11Rmd](https://user-images.githubusercontent.com/32690638/109555909-bf200b80-7a9b-11eb-973f-a3b15b8665b5.PNG)
![CaptureIE11](https://user-images.githubusercontent.com/32690638/109555915-bfb8a200-7a9b-11eb-97f7-7155060c7654.PNG)

**Comment by rich-iannone** [comment]
Fixed by https://github.com/rstudio/fontawesome/pull/40.
