### ISSUE TITLE
Can't change right margin with margin_right

### ISSUE THREAD

**Issue by aosmith16** [rstudio/fontawesome#53]
I noticed that all my icons were slightly pushed to the left with the newest version of **fontawesome**.  I attempted to change this via the new `margin_right` argument and, well, nothing happened, no matter what value I used.

I delved a tiny bit into the code and as far as I can tell that argument is never used in within the `fa()` function.  Instead the right margin is hard-coded at ".2em".  Am I missing something?

**Comment by rich-iannone** [comment]
This is my mistake, sorry that it broke your existing document. I'd like to fix by making `margin_right` functional, defaulting to the `"auto"` margin (essentially `0`, same as before the update), and adding a `margin_left` argument (default of `"auto"`). Once this is fixed, a patch release of the package will sent to CRAN.
