### ISSUE TITLE
Selectize example (not an issue)

### ISSUE THREAD

**Issue by stla** [rstudio/fontawesome#64]
Hello,

  [Here](https://stackoverflow.com/q/68509486/1100107) I did an example of **font-awesome** icons in the items of a `selectizeInput`.
  This is not an issue, just wanted to share. And maybe you have some comments, perhaps an easier way ?

Cheers.

**Comment by rich-iannone** [comment]
Love this! Thanks for sharing. This is something we could consider putting into the docs or in an article. The use case here is really compelling.
