### ISSUE TITLE
Warning in third party package shinymanager

### ISSUE THREAD

**Issue by dmenne** [rstudio/fontawesome#65]
I raised this issue: 

https://github.com/datastorm-open/shinymanager/issues/117#issue-951778631

which was closed because it supposedly is an issue with this package. Not sure what is correct.

The `name` provided ('sign-out') is deprecated in Font Awesome 5:
* please consider using 'sign-out-alt' or 'fas fa-sign-out-alt' instead
* use the `verify_fa = FALSE` to deactivate these messages
This Font Awesome icon ('close') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`

**Comment by rich-iannone** [comment]
Thanks for raising the issue but it seems now like something that can be fixed in shinymanager. Will close now.
