### ISSUE TITLE
Full names not being respected in fa_i

### ISSUE THREAD

**Issue by neilhatfield** [rstudio/fontawesome#68]
Currently, full names of icons aren't being respected by the `fa_i` function. For example `fa_i("far fa-sqaure")` will get translated to `<i class="fa fa-far fa-square"></i>`. In essence, `fa_i` is prepending "fa" as the style and to the name, regardless of whether or not a full name is provided.

A solution would be examine whether the submitted name is a full name or shortened, potentially by checking whether there is a space in the name. If a full name is provided, then that should be used for the internal `iconClass` object rather than the `paste0` output.

**Comment by rich-iannone** [comment]
Thanks for reporting and for the recommendations on how to resolve this issue. We will get to a fix on this quite soon.
