### ISSUE TITLE
Update styles

### ISSUE THREAD

**Issue by neilhatfield** [rstudio/fontawesome#69]
The `fa_i` function is using "fa" as the style (except when the name appears in the brands list). However, "fa" is depreciated in FontAwesome 5 (see https://fontawesome.com/v5.15/how-to-use/on-the-web/referencing-icons/basic-use). The default is now "fas". While "fa" currently will resolve to "fas", it is unclear for how long this will last. Additionally, there are other styles, such as "far" which do have free icons (e.g., "far fa-square") which are getting re-written (see #68). Perhaps a solution would be to add an argument for the style ("far", "fas", "fab", etc.) that has a default of "far" and a check/resolve against "fa".

**Comment by rich-iannone** [comment]
Thanks for the detailed look at this. I really like your suggestions and a fix will be happening soon!
