### ISSUE TITLE
placement of fa glyphs - web only? free only?

### ISSUE THREAD

**Issue by houstonhaynes** [rstudio/fontawesome#7]
I'm having trouble placing an icon in a more-or-less in-line fashion (as a logo next a "Back to Top" link that takes the user to the #TOC bookmark). See the code quote below...

`r fa("arrow-square-up",  fill = "tomato")`

...which yields no result on the page. However if I use "r-project" as the icon they all show. (see attached image)

Did I miss a memo on the glyphs that were available? Thanks!
![h3portfoliositefontawesomer-projectsonly](https://user-images.githubusercontent.com/8174976/43169890-a184cc5a-8f57-11e8-845b-b70180bc51ff.PNG)

**Comment by rich-iannone** [comment]
Thanks for pointing out this issue and sorry for the confusion. The icon glyphs included are only from the `free` tier and `arrow-square-up` and its variations are from the `pro` collection. An alternative (free) glyph is: `arrow-circle-up`.

I'll make this more obvious in the README and the help docs and will close the issue once that's complete.

**Comment by houstonhaynes** [comment]
Awesome - FWIW I had licensed the font for a previous site and was accustomed to calling up anything in the kit. Here I'm happy to stay with the freebies.

**Comment by under-score** [comment]
How can I generate a list of icons included in the library?
