### ISSUE TITLE
Allow fractional height and width attributes

### ISSUE THREAD

**Issue by tuttoaposto** [rstudio/fontawesome#73]
### Discussed in https://github.com/rstudio/fontawesome/discussions/71

<div type='discussions-op-text'>

<sup>Originally posted by **tuttoaposto** November  3, 2021</sup>
The function get_length_value_unit() supports integer length (e.g. 1em) but not fractional length (e.g. 0.88em) in V0.2.2. Is it possible to get this updated :pray: and make fontawesome really awesome :star2:?? This can be achieved by, for example, changing 
<pre>
grepl("^[0-9]+[a-z]+$", css_length)
</pre> to 
<pre>
grepl("^[0-9]+<b>[.][0-9]+)?</b>[a-z]+$", css_length)
</pre>

and

<pre>
unit <- sub("^[0-9]+", "", css_length)
</pre> to
<pre>
unit <- sub("^[0-9]+<b>([.][0-9]+)?</b>", "", css_length)
</pre>

Thanks you!</div>

**Comment by rich-iannone** [comment]
Sorry for the delay in getting to this. Definitely this will be changed to allow for fractional length units!
