### ISSUE TITLE
CRAN timeline?

### ISSUE THREAD

**Issue by vnijs** [rstudio/fontawesome#8]
@rich-iannone I just found this repo as I was searching for the best way to include fontawesome icons in rmarkdown docs. One option I found [here](https://github.com/ropensci/ozunconf17/issues/31) is shown below. The `fontawesome` package looks very interesting as well. Could you perhaps comment on if/when the `fontawsome` package will be on CRAN?

    ```{r setup, include = FALSE}
    htmltools::tagList(rmarkdown::html_dependency_font_awesome())
    ```

**Comment by leowee** [comment]
Second this!

In my work, I can only use CRAN packages because of a Proxy. You would help a lot if you managed to make this happen

**Comment by jkfding** [comment]
Yep, this is an awesome package. It makes adding these icons way easier than any other method. I'm also hoping to see it on CRAN soon.

**Comment by rich-iannone** [comment]
It’s on CRAN now. Sorry for the long wait but it has finally happened!
