### ISSUE TITLE
Include fontawesome beta version 6 icons

### ISSUE THREAD

**Issue by mdzievit** [rstudio/fontawesome#80]
A beta release of version 6 icons is now available. Can we include these in the next release? They include some basic numerals that would be great to have. 

Alternatively, a function where we could pass an icon file but still have the same output type would help in-between release. I can download the beta version 6 to my machine but no way to pull those into the package (That I know about).

Thanks!

**Comment by lvalnegri** [comment]
I'm not sure what's your exact use case, but here briefly how I've managed to make v6 work with leaflet and shiny on my own linux website, you can add the following to your own package to make it work transparently:

- download the zip file https://fontawesome.com/download
- save it in a folder under your website, say `/var/www/html/fa`
- define the following two strings:

```
registerPlugin <- function(map, plugin) {
    map$dependencies <- c(map$dependencies, list(plugin))
    map
}
```
```
faPlugin <- htmltools::htmlDependency(
    name = 'font-awesome',
    version = '99.0',
    src = c(href = 'https://ipaddress/fa'),
    stylesheet = 'css/all.css'
)
```
- in the leaflet call add a reference to the plugin
   ```leaflet() |> registerPlugin(faPlugin)```
  and use `addAwesomeMarkers` with 
  ```icon = ~makeAwesomeIcon(icon = X, library = 'fa', markerColor = ..., iconColor = ...)```
- in shiny add a reference to the plugin and the css at the top of your ui: 
   ```
    faPlugin,
    tags$head( tags$style("@import url('https://ipaddress/fa/all.css;')")),
   ```
you should also add a `verify_fa = FALSE` to any icon call to avoid annoying warnings

**Comment by rich-iannone** [comment]
Closing this new as https://github.com/rstudio/fontawesome/pull/85 adds the FA v6.1 free icon set.
