### ISSUE TITLE
Add an article in pkgdown website to show all the possible icon available with the embeded version

### ISSUE THREAD

**Issue by cderv** [rstudio/fontawesome#81]
Idea following a discussion with @EricJC24 : 

It is not easy to know which icon is really available - all the more if the fontawesome version of the main website is not the same as the one embeded. 

Do you think @rich-iannone it would be interesting and possible to add an article in the website showing all the available icon ? Or maybe that would be too much 😅 

Just leaving this here, but feel free to dismiss. 😉

**Comment by rich-iannone** [comment]
This is very necessary (and something I unfortunately delayed). Check this out, I did something similar with lineawesome icons in the {omsvg} package:

<img width="1015" alt="lineawesome" src="https://user-images.githubusercontent.com/5612024/151573814-4f2896ca-dd83-445b-8e7c-da09e2a2210f.png">

You can get that with `info_lineawesome()`. I could have a similar thing here, but improve upon it (publish tables of icons in pkgdown articles and also create a function).

**Comment by cderv** [comment]
I knew I saw that somewhere !! That was in the other package you showed me some time ago 😅 

Yes something like this would be great !

**Comment by jhk0530** [comment]
This [Mac 30th Anniversary Icons page](https://rknightuk.github.io/mac-30-font-svg/) can be one example for reference

<img width="1407" alt="스크린샷 2023-01-27 오후 10 06 45" src="https://user-images.githubusercontent.com/6457691/215094173-cac4716a-f406-4611-ade6-74dfeee2ab7e.png">

**Comment by rich-iannone** [comment]
Now done.
