### ISSUE TITLE
FontAwesome licensing woes

### ISSUE THREAD

**Issue by eebrown** [rstudio/fontawesome#86]
Since FontAwesome v5, the build system to generate the font files has not been released and is proprietary (https://github.com/FortAwesome/Font-Awesome/issues/13467). Some projects, including Debian, consider that the binary fonts are therefore not open source. Debian has not been able to properly package versions >= v5 as a result (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902981#27) 

Some projects have moved to ForkAwesome (https://github.com/ForkAwesome/Fork-Awesome), a fully open source fork of v4, with compatibility aliases to v5, instead.

It is not clear to me whether CRAN interprets open source the same as Debian.

Either way, would this project consider switching to ForkAwesome to alleviate licensing issues on related projects? It's particularly important in Debian because shiny has this package as a dependency.

**Comment by rich-iannone** [comment]
CRAN has not raised the issue regarding licensing so I'm assuming it's not a problem. As such, we won't consider moving away from using the icon files from the FontAwesome project.
